---
- hosts: localhost
  connection: local 
  become: true

  tasks:

    - name: Download GPG
      apt_key: 
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        keyring: /usr/share/keyrings/elastic.gpg
        state: present
 
    - name: Install dependencies
      apt:
        pkg: 
        - apt-transport-https
        state: present

    - name: Add elastic repostitory
      apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main
        filename: elastic-7.x
        state: present

    - name: Update cache
      apt:
       update_cache: yes

    - name: Install beats
      apt:
        pkg:
        - metricbeat
        state: present 

    - name: Start Beats service 
      service:
        name: metricbeat 
        state: started
        enabled: yes

