---
- hosts: localhost
  become: true
  vars:
  - jenkins_key: /usr/share/keyrings/jenkins-keyring.asc
  - jenkins_key_url: https://pkg.jenkins.io/debian-stable/jenkins.io.key

  pre_tasks:
  - name: Ensure /usr/share/keyrings exists
    ansible.builtin.file:
      path: /usr/share/keyrings/
      state: directory

  - name: Download GPG key 
    ansible.builtin.shell: >
        curl -fsSL {{ jenkins_key_url }} | sudo tee {{ jenkins_key }} > /dev/null
        creates={{ jenkins_key }}

  - name: Add Download repository
    ansible.builtin.shell: >
      echo "deb [signed-by={{ jenkins_key }} ] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null

  - name: Install Dependencies
    ansible.builtin.apt:
      pkg:
      - fontconfig
      - openjdk-11-jre

  - name: Apt key
    ansible.builtin.apt_key:
      url: https://pkg.jenkins.io/debian-stable/jenkins.io.key
   
  - name: Install jenkins
    ansible.builtin.apt:
      name: jenkins 
      update_cache: yes
      state: latest

  - name: Start Jenkins server
    ansible.builtin.service:
      name: jenkins
      state: started
      enabled: yes
